#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["typer>=0.15.0"]
# ///
"""Turn this template into a real project, in place.

Run once, immediately after creating a repository from the template:

    uv run bootstrap.py
    uv run bootstrap.py --name my-package --description "Does a thing."

Values are inferred from the git remote where possible, and anything still
missing is prompted for. The script rewrites the template's own name out of
every tracked file, renames the package directory, replaces the README, and
finally deletes itself.

Deliberately dumb: a plain find-and-replace over the tracked file list, so
`git diff` tells you exactly what happened. Use `--dry-run` to see the file
list without touching anything.
"""

import re
import subprocess
from pathlib import Path
from typing import Annotated

import typer

ROOT = Path(__file__).resolve().parent

# The strings being replaced.
TEMPLATE_OWNER = "jmarshrossney"
TEMPLATE_REPO = "python-package-template"
TEMPLATE_PKG = "python_package_template"
TEMPLATE_DESCRIPTION = (
    "A template for Python packages built with "
    "uv, just, ruff, pyright, pytest and zensical."
)

# Files never rewritten. `uv.lock` is regenerated by `uv sync`; rewriting it by
# hand would leave a lockfile that disagrees with its own hashes. README.md is
# replaced wholesale, and this script deletes itself.
SKIP = frozenset({"uv.lock", "README.md", "bootstrap.py"})

NEW_README = """# {repo}

{description}

## Installation

```sh
pip install {repo}
```

## Usage

```python
import {pkg}
```

## Development

See [CONTRIBUTING.md](CONTRIBUTING.md). In short: `uv sync`, then `just`.
"""

NEXT_STEPS = """
Done. Next:
  1. uv sync      # regenerate uv.lock under the new name
  2. git diff     # check the rewrites
  3. just         # lint, typecheck, test, docs
  4. Update LICENSE, docs/, and the logo in zensical.toml
  5. Enable GitHub Pages (Settings -> Pages -> GitHub Actions)
"""


def git(*args: str) -> str | None:
    """Run a git command, returning stripped stdout, or None on failure."""
    try:
        out = subprocess.run(
            ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    return out.stdout.strip() or None


def infer_from_remote() -> tuple[str | None, str | None]:
    """Return (owner, repo) parsed from the `origin` remote, if available."""
    url = git("remote", "get-url", "origin")
    if not url:
        return None, None
    match = re.search(r"[:/]([^/:]+)/([^/]+?)(?:\.git)?$", url)
    if not match:
        return None, None
    return match.group(1), match.group(2)


def to_package_name(repo: str) -> str:
    """Convert a repository name to an importable package name."""
    pkg = re.sub(r"[^0-9a-zA-Z]+", "_", repo).strip("_").lower()
    if not pkg or not pkg[0].isalpha():
        pkg = f"pkg_{pkg}".rstrip("_")
    return pkg


def candidate_files() -> list[Path]:
    """Every text file git knows about, minus the ones we must not rewrite.

    Discovered rather than hardcoded, so the list cannot drift as the template
    grows. `--others` is included because a repository created from a template
    may not have committed anything yet.
    """
    listing = git("ls-files", "--cached", "--others", "--exclude-standard")
    if not listing:
        raise typer.BadParameter("no files found -- is this a git repository?")
    paths = []
    for name in listing.splitlines():
        if name in SKIP:
            continue
        path = ROOT / name
        try:
            path.read_text()
        except (OSError, UnicodeDecodeError):
            continue  # missing, or not text
        paths.append(path)
    return paths


def rewrite(path: Path, replacements: list[tuple[str, str]]) -> bool:
    """Apply replacements to a file. Returns True if the file changed."""
    original = path.read_text()
    updated = original
    for old, new in replacements:
        updated = updated.replace(old, new)
    if updated == original:
        return False
    path.write_text(updated)
    return True


def main(
    name: Annotated[
        str | None, typer.Option(help="Project (and distribution) name.")
    ] = None,
    owner: Annotated[
        str | None, typer.Option(help="GitHub user or organisation.")
    ] = None,
    description: Annotated[
        str | None, typer.Option(help="One-line project description.")
    ] = None,
    package: Annotated[
        str | None, typer.Option(help="Import name. Default: derived from --name.")
    ] = None,
    yes: Annotated[
        bool, typer.Option("--yes", "-y", help="Skip all prompts and confirmation.")
    ] = False,
    dry_run: Annotated[
        bool, typer.Option(help="Report what would change, then exit.")
    ] = False,
) -> None:
    """Turn this template into a real project, in place."""
    remote_owner, remote_repo = infer_from_remote()

    if (remote_owner, remote_repo) == (TEMPLATE_OWNER, TEMPLATE_REPO) and not (
        name and owner
    ):
        typer.echo(
            "Refusing to bootstrap: the git remote still points at the template "
            f"itself ({TEMPLATE_OWNER}/{TEMPLATE_REPO}).\n"
            "Create a repository from the template first, or pass --name and "
            "--owner explicitly.",
            err=True,
        )
        raise typer.Exit(1)

    if yes:
        repo, owner = name or remote_repo, owner or remote_owner
        if not repo or not owner:
            typer.echo("--yes needs --name and --owner when there is no git remote.")
            raise typer.Exit(1)
        description = description or f"The {repo} package."
    else:
        repo = name or typer.prompt("Project name", default=remote_repo)
        owner = owner or typer.prompt("GitHub owner", default=remote_owner)
        description = description or typer.prompt(
            "Description", default=f"The {repo} package."
        )

    pkg = package or to_package_name(repo)

    typer.echo(f"\n  name        {repo}")
    typer.echo(f"  package     {pkg}")
    typer.echo(f"  owner       {owner}")
    typer.echo(f"  description {description}")
    typer.echo(f"  docs url    https://{owner.lower()}.github.io/{repo}\n")

    replacements = [
        # Pages URL before the owner/repo pair, which is before the bare names.
        (
            f"https://{TEMPLATE_OWNER}.github.io/{TEMPLATE_REPO}",
            f"https://{owner.lower()}.github.io/{repo}",
        ),
        (f"{TEMPLATE_OWNER}/{TEMPLATE_REPO}", f"{owner}/{repo}"),
        (f"github.com/{TEMPLATE_OWNER}", f"github.com/{owner}"),
        (TEMPLATE_DESCRIPTION, description),
        (TEMPLATE_PKG, pkg),
        (TEMPLATE_REPO, repo),
    ]

    if dry_run:
        typer.echo("Would rewrite:")
        for path in candidate_files():
            original = path.read_text()
            if any(old in original for old, _ in replacements):
                typer.echo(f"  {path.relative_to(ROOT)}")
        typer.echo(f"Would rename src/{TEMPLATE_PKG}/ -> src/{pkg}/")
        typer.echo("Would replace README.md and delete bootstrap.py")
        return

    if not yes and not typer.confirm("Proceed?"):
        raise typer.Exit(1)

    for path in candidate_files():
        if rewrite(path, replacements):
            typer.echo(f"  rewrote {path.relative_to(ROOT)}")

    src, dest = ROOT / "src" / TEMPLATE_PKG, ROOT / "src" / pkg
    if src.exists() and src != dest:
        src.rename(dest)
        typer.echo(f"  renamed src/{TEMPLATE_PKG}/ -> src/{pkg}/")

    (ROOT / "README.md").write_text(
        NEW_README.format(repo=repo, pkg=pkg, description=description)
    )
    typer.echo("  replaced README.md")

    Path(__file__).unlink()
    typer.echo("  deleted bootstrap.py")

    typer.echo(NEXT_STEPS)


if __name__ == "__main__":
    typer.run(main)
